from dataclasses import dataclass, field
from typing import Any, Literal, Protocol, Sequence

__all__ = ['GrokMessage', 'GrokInput', 'GrokRequest', 'GrokBatchRequest', 'GrokResponse', 'GrokBatchResponse', 'GrokStreamingChunk', 'LLMStreamingChunkProtocol', 'SaveMode', 'Role']

type SaveMode = Literal['none', 'json_files', 'postgres']
type Role = Literal['system', 'user', 'assistant', 'developer']
class LLMStreamingChunkProtocol(Protocol):
    @property
    def text(self) -> str: ...
    @property
    def finish_reason(self) -> str | None: ...
    @property
    def tool_calls_delta(self) -> list[dict[str, Any]] | None: ...
    @property
    def is_final(self) -> bool: ...
    @property
    def raw(self) -> dict[str, Any]: ...

@dataclass(frozen=True)
class GrokMessage:
    role: Role
    content: str | list[dict[str, Any]]
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, msg_dict: dict[str, Any]) -> GrokMessage: ...

@dataclass(frozen=True)
class GrokInput:
    messages: tuple[GrokMessage, ...] = field(default_factory=tuple)
    def to_list(self) -> list[dict[str, Any]]: ...
    @classmethod
    def from_str(cls, text: str) -> GrokInput: ...
    @classmethod
    def from_list(cls, messages: Sequence[dict[str, Any] | GrokMessage] | None = None) -> GrokInput: ...

@dataclass(frozen=True)
class GrokRequest:
    model: str
    input: GrokInput = field(default_factory=GrokInput)
    temperature: float | None = ...
    max_tokens: int | None = ...
    top_p: float | None = ...
    include_reasoning: bool = ...
    reasoning_effort: Literal['low', 'medium', 'high'] | None = ...
    tools: list[dict[str, Any]] | None = ...
    response_format: dict[str, Any] | None = ...
    save_mode: SaveMode = ...
    prompt_cache_key: str | None = ...
    batch_request_id: str | None = ...
    def to_sdk_messages(self) -> list[dict[str, Any]]: ...
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> GrokRequest: ...
    def with_updates(self, **updates: Any) -> GrokRequest: ...

@dataclass(frozen=True)
class GrokBatchRequest:
    batch_name: str
    requests: list[GrokRequest] = field(default_factory=list)
    def to_sdk_batch_requests(self) -> list[Any]: ...

@dataclass(frozen=True)
class GrokResponse:
    id: str
    created_at: int
    model: str
    output: Sequence[dict[str, Any]] = field(default_factory=list)
    usage: dict[str, Any] | None = ...
    status: Literal['completed', 'in_progress', 'incomplete'] | None = ...
    raw: dict[str, Any] = field(default_factory=dict)
    reasoning_text: str | None = ...
    @property
    def text(self) -> str: ...
    @property
    def tool_calls(self) -> list[dict[str, Any]]: ...
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> GrokResponse: ...

@dataclass(frozen=True)
class GrokBatchResponse:
    batch_id: str
    results: tuple[dict[str, Any], ...]
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> GrokBatchResponse: ...

@dataclass(frozen=True)
class GrokStreamingChunk:
    text: str = ...
    finish_reason: str | None = ...
    tool_calls_delta: list[dict[str, Any]] | None = ...
    is_final: bool = ...
    raw: dict[str, Any] = field(default_factory=dict)
