from dataclasses import dataclass, field
from typing import Any, Literal, Sequence

from pydantic import BaseModel

type SaveMode = Literal["none", "json_files", "postgres"]
type Role = Literal["system", "user", "assistant", "developer"]

@dataclass(frozen=True)
class GrokMessage:
    role: Role
    content: str | list[dict[str, Any]]
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, msg_dict: dict[str, Any]) -> GrokMessage: ...

@dataclass(frozen=True)
class GrokInput:
    messages: tuple[GrokMessage, ...]
    def to_list(self) -> list[dict[str, Any]]: ...
    @classmethod
    def from_list(cls, msg_list: list[dict[str, Any]]) -> GrokInput: ...

@dataclass(frozen=True)
class GrokRequest:
    input: GrokInput
    model: str = ...
    temperature: float | None = ...
    top_p: float | None = ...
    max_output_tokens: int | None = ...
    store: bool = ...
    tools: list[dict[str, Any]] | None = ...
    tool_choice: str | dict[str, Any] | None = ...
    parallel_tool_calls: bool | None = ...
    structured_schema: dict[str, Any] | type[BaseModel] | None = ...
    def to_dict(self) -> dict[str, Any]: ...

@dataclass(frozen=True)
class GrokResponse:
    id: str
    created_at: int
    model: str
    output: Sequence[dict[str, Any]] = field(default_factory=list)
    usage: dict[str, Any] | None = ...
    status: Literal["completed", "in_progress", "incomplete"] | None = ...
    raw: dict[str, Any] = field(default_factory=dict)
    @property
    def text(self) -> str: ...
    @property
    def first_message(self) -> dict[str, Any] | None: ...
    @property
    def tool_calls(self) -> list[dict[str, Any]]: ...
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> GrokResponse: ...
