from dataclasses import dataclass, field
from typing import Any, Literal, Protocol

class LLMStreamingChunkProtocol(Protocol):
    @property
    def text(self) -> str: ...
    @property
    def finish_reason(self) -> str | None: ...
    @property
    def tool_calls_delta(self) -> list[dict[str, Any]] | None: ...
    @property
    def is_final(self) -> bool: ...
    @property
    def raw(self) -> dict[str, Any]: ...
type Role = Literal['system', 'user', 'assistant']

@dataclass(frozen=True)
class OllamaMessage:
    role: Role
    content: str | list[dict[str, Any]]
    def to_dict(self) -> dict[str, Any]: ...
    @classmethod
    def from_dict(cls, msg_dict: dict[str, Any]) -> OllamaMessage: ...

@dataclass(frozen=True)
class OllamaInput:
    messages: tuple[OllamaMessage, ...]
    def to_list(self) -> list[dict[str, Any]]: ...
    @classmethod
    def from_list(cls, msg_list: list[dict[str, Any]]) -> OllamaInput: ...

@dataclass(frozen=True)
class OllamaRequest:
    input: OllamaInput
    model: str = ...
    temperature: float | None = ...
    top_p: float | None = ...
    max_tokens: int | None = ...
    def to_payload(self) -> dict[str, Any]: ...
    def get_endpoint(self) -> str: ...

@dataclass(frozen=True)
class OllamaResponse:
    model: str
    message: dict[str, Any]
    done: bool
    total_duration: int | None = ...
    raw: dict[str, Any] = field(default_factory=dict)
    @property
    def text(self) -> str: ...
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> OllamaResponse: ...

@dataclass(frozen=True)
class OllamaStreamingChunk:
    model: str
    message: dict[str, Any]
    done: bool
    raw: dict[str, Any] = field(default_factory=dict)
    @property
    def text(self) -> str: ...
    @property
    def finish_reason(self) -> str | None: ...
    @property
    def tool_calls_delta(self) -> list[dict[str, Any]] | None: ...
    @property
    def is_final(self) -> bool: ...
    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> OllamaStreamingChunk: ...
