-- =============================================
-- Complete Test Database Setup for ai_api
-- Run as the PostgreSQL superuser (postgres):
--     psql -h 127.0.0.1 -p 5432 -U postgres -d testdb -f setup_test_db.sql
-- =============================================
-- 1. Required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 2. Providers (small lookup table – no partitioning)
CREATE TABLE IF NOT EXISTS providers (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  description text
);

CREATE INDEX IF NOT EXISTS ix_providers_name ON providers (name);

-- 3. Requests (partitioned by tstamp)
CREATE TABLE IF NOT EXISTS requests (
  idx bigint GENERATED ALWAYS AS IDENTITY,
  tstamp timestamptz NOT NULL DEFAULT now(),
  provider_id integer NOT NULL REFERENCES providers (id),
  endpoint jsonb NOT NULL,
  request_id uuid NOT NULL,
  request jsonb NOT NULL,
  meta jsonb NOT NULL,
  PRIMARY KEY (idx, tstamp)
)
PARTITION BY RANGE (tstamp);

-- Create today's partition (2026-04-06)
CREATE TABLE IF NOT EXISTS requests_2026_04_06 PARTITION OF requests
FOR VALUES FROM ('2026-04-06 00:00:00+00') TO ('2026-04-07 00:00:00+00');

CREATE INDEX IF NOT EXISTS ix_requests_tstamp ON requests (tstamp);

CREATE INDEX IF NOT EXISTS ix_requests_provider_id ON requests (provider_id);

CREATE INDEX IF NOT EXISTS ix_requests_request_id ON requests (request_id);

-- Idempotent UNIQUE constraint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT
      1
    FROM
      pg_constraint
    WHERE
      conname = 'uq_requests_request_id_tstamp'
      AND conrelid = 'requests'::regclass) THEN
  ALTER TABLE requests
    ADD CONSTRAINT uq_requests_request_id_tstamp UNIQUE (request_id, tstamp);
END IF;
END
$$;

-- 4. Responses (partitioned by tstamp)
CREATE TABLE IF NOT EXISTS responses (
  idx bigint GENERATED ALWAYS AS IDENTITY,
  tstamp timestamptz NOT NULL DEFAULT now(),
  provider_id integer NOT NULL REFERENCES providers (id),
  endpoint jsonb NOT NULL,
  request_id uuid NOT NULL,
  request_tstamp timestamptz NOT NULL,
  response_id uuid NOT NULL,
  response jsonb NOT NULL,
  meta jsonb NOT NULL,
  PRIMARY KEY (idx, tstamp)
)
PARTITION BY RANGE (tstamp);

-- Create today's partition
CREATE TABLE IF NOT EXISTS responses_2026_04_06 PARTITION OF responses
FOR VALUES FROM ('2026-04-06 00:00:00+00') TO ('2026-04-07 00:00:00+00');

CREATE INDEX IF NOT EXISTS ix_responses_tstamp ON responses (tstamp);

CREATE INDEX IF NOT EXISTS ix_responses_provider_id ON responses (provider_id);

CREATE INDEX IF NOT EXISTS ix_responses_request_id ON responses (request_id);

CREATE INDEX IF NOT EXISTS ix_responses_response_id ON responses (response_id);

CREATE INDEX IF NOT EXISTS ix_responses_request_id_tstamp ON responses (request_id, request_tstamp);

-- Idempotent FOREIGN KEY constraint
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT
      1
    FROM
      pg_constraint
    WHERE
      conname = 'fk_responses_request_id_tstamp'
      AND conrelid = 'responses'::regclass) THEN
  ALTER TABLE responses
    ADD CONSTRAINT fk_responses_request_id_tstamp FOREIGN KEY (request_id, request_tstamp) REFERENCES requests (request_id, tstamp) ON DELETE CASCADE;
END IF;
END
$$;

-- 5. Logs (partitioned by tstamp)
CREATE TABLE IF NOT EXISTS logs (
  idx bigint GENERATED ALWAYS AS IDENTITY,
  tstamp timestamptz NOT NULL DEFAULT now(),
  loglvl text NOT NULL,
  logger text NOT NULL,
  message text NOT NULL,
  obj jsonb,
  PRIMARY KEY (idx, tstamp)
)
PARTITION BY RANGE (tstamp);

-- Create today's partition
CREATE TABLE IF NOT EXISTS logs_2026_04_06 PARTITION OF logs
FOR VALUES FROM ('2026-04-06 00:00:00+00') TO ('2026-04-07 00:00:00+00');

CREATE INDEX IF NOT EXISTS ix_logs_tstamp ON logs (tstamp);

-- ========================================================
-- GRANT PRIVILEGES TO TEST USER
-- ========================================================
GRANT ALL PRIVILEGES ON TABLE providers TO testuser;

GRANT ALL PRIVILEGES ON TABLE requests TO testuser;

GRANT ALL PRIVILEGES ON TABLE responses TO testuser;

GRANT ALL PRIVILEGES ON TABLE logs TO testuser;

GRANT ALL PRIVILEGES ON TABLE requests_2026_04_06 TO testuser;

GRANT ALL PRIVILEGES ON TABLE responses_2026_04_06 TO testuser;

GRANT ALL PRIVILEGES ON TABLE logs_2026_04_06 TO testuser;

-- ========================================================
-- MAKE testuser THE OWNER OF THE PARENT TABLES
-- This is REQUIRED so testuser can create new daily partitions
-- ========================================================
ALTER TABLE requests OWNER TO testuser;

ALTER TABLE responses OWNER TO testuser;

ALTER TABLE logs OWNER TO testuser;

-- ========================================================
-- Verification queries (run these after execution)
-- ========================================================
-- SELECT tablename FROM pg_tables WHERE schemaname = 'public' ORDER BY tablename;
-- SELECT * FROM providers;   -- should be empty
