-- =============================================
-- Complete Test Database Setup for ai_api
-- Run as the PostgreSQL superuser (postgres):
--     psql -h 127.0.0.1 -p 5432 -U postgres -f setup_test_db.sql
-- =============================================
-- ========================================================
-- Database schema for testdb
-- Generated from db_responses_schema.py (April 2026)
-- Creates: providers, requests, responses, logs
-- with daily RANGE partitioning and all indexes/constraints
-- Run as the PostgreSQL superuser (postgres):
--     psql -h 127.0.0.1 -p 5432 -U postgres -f createTestDB.sql
-- ========================================================

-- 1. Required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 2. Providers (small lookup table – no partitioning)
CREATE TABLE IF NOT EXISTS providers (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    description TEXT
);

CREATE INDEX IF NOT EXISTS ix_providers_name ON providers (name);

-- 3. Requests (partitioned by tstamp)
CREATE TABLE IF NOT EXISTS requests (
    idx         BIGINT GENERATED ALWAYS AS IDENTITY,
    tstamp      TIMESTAMPTZ NOT NULL DEFAULT now(),
    provider_id INTEGER NOT NULL REFERENCES providers(id),
    endpoint    JSONB NOT NULL,
    request_id  UUID NOT NULL,
    request     JSONB NOT NULL,
    meta        JSONB NOT NULL,
    PRIMARY KEY (idx, tstamp)
) PARTITION BY RANGE (tstamp);

-- Create today's partition (2026-04-04)
CREATE TABLE IF NOT EXISTS requests_2026_04_04
    PARTITION OF requests
    FOR VALUES FROM ('2026-04-04 00:00:00+00') TO ('2026-04-05 00:00:00+00');

-- Indexes and constraints for requests
CREATE INDEX IF NOT EXISTS ix_requests_tstamp      ON requests (tstamp);
CREATE INDEX IF NOT EXISTS ix_requests_provider_id ON requests (provider_id);
CREATE INDEX IF NOT EXISTS ix_requests_request_id  ON requests (request_id);

ALTER TABLE requests
    ADD CONSTRAINT uq_requests_request_id_tstamp
    UNIQUE (request_id, tstamp);

-- 4. Responses (partitioned by tstamp + composite FK to requests)
CREATE TABLE IF NOT EXISTS responses (
    idx             BIGINT GENERATED ALWAYS AS IDENTITY,
    tstamp          TIMESTAMPTZ NOT NULL DEFAULT now(),
    provider_id     INTEGER NOT NULL REFERENCES providers(id),
    endpoint        JSONB NOT NULL,
    request_id      UUID NOT NULL,
    request_tstamp  TIMESTAMPTZ NOT NULL,
    response_id     UUID NOT NULL,
    response        JSONB NOT NULL,
    meta            JSONB NOT NULL,
    PRIMARY KEY (idx, tstamp)
) PARTITION BY RANGE (tstamp);

-- Create today's partition
CREATE TABLE IF NOT EXISTS responses_2026_04_04
    PARTITION OF responses
    FOR VALUES FROM ('2026-04-04 00:00:00+00') TO ('2026-04-05 00:00:00+00');

-- Indexes for responses
CREATE INDEX IF NOT EXISTS ix_responses_tstamp          ON responses (tstamp);
CREATE INDEX IF NOT EXISTS ix_responses_provider_id     ON responses (provider_id);
CREATE INDEX IF NOT EXISTS ix_responses_request_id      ON responses (request_id);
CREATE INDEX IF NOT EXISTS ix_responses_response_id     ON responses (response_id);
CREATE INDEX IF NOT EXISTS ix_responses_request_id_tstamp ON responses (request_id, request_tstamp);

-- Composite foreign key (request_id + request_tstamp) → requests
ALTER TABLE responses
    ADD CONSTRAINT fk_responses_request_id_tstamp
    FOREIGN KEY (request_id, request_tstamp)
    REFERENCES requests (request_id, tstamp)
    ON DELETE CASCADE;

-- 5. Logs (partitioned by tstamp)
CREATE TABLE IF NOT EXISTS logs (
    idx     BIGINT GENERATED ALWAYS AS IDENTITY,
    tstamp  TIMESTAMPTZ NOT NULL DEFAULT now(),
    loglvl  TEXT NOT NULL,
    logger  TEXT NOT NULL,
    message TEXT NOT NULL,
    obj     JSONB,
    PRIMARY KEY (idx, tstamp)
) PARTITION BY RANGE (tstamp);

-- Create today's partition
CREATE TABLE IF NOT EXISTS logs_2026_04_04
    PARTITION OF logs
    FOR VALUES FROM ('2026-04-04 00:00:00+00') TO ('2026-04-05 00:00:00+00');

-- Index for logs
CREATE INDEX IF NOT EXISTS ix_logs_tstamp ON logs (tstamp);

-- ========================================================
-- Verification queries (run these after execution)
-- ========================================================
-- SELECT tablename FROM pg_tables WHERE schemaname = 'public' ORDER BY tablename;
-- SELECT * FROM providers;   -- should be empty
