import asyncpg
import grpc
from _typeshed import Incomplete
from typing import Any

class GrokError(Exception):
    message: Incomplete
    details: Incomplete
    def __init__(self, message: str, details: dict[str, Any] | None = None) -> None: ...

class GrokLoggerError(GrokError): ...
class GrokLoggerInitializationError(GrokLoggerError): ...
class GrokInfopypgError(GrokError): ...
class GrokInfopypgSettingsError(GrokInfopypgError): ...
class GrokInfopypgPoolError(GrokInfopypgError): ...
class GrokPostgresError(GrokError): ...
class GrokPostgresConnectionError(GrokPostgresError, asyncpg.ConnectionDoesNotExistError): ...
class GrokPostgresQueryError(GrokPostgresError, asyncpg.PostgresError): ...
class GrokPostgresConnectionError(GrokPostgresError): ...
class GrokPostgresQueryError(GrokPostgresError): ...
class GrokAPIError(GrokError): ...
class GrokAPIConnectionError(GrokAPIError, grpc.RpcError): ...
class GrokAPIAuthenticationError(GrokAPIError, grpc.RpcError): ...
class GrokAPIConnectionError(GrokAPIError): ...
class GrokAPIAuthenticationError(GrokAPIError): ...
class GrokAPIInvalidRequestError(GrokAPIError): ...
class GrokAPIRateLimitError(GrokAPIError): ...
class GrokClientError(GrokError): ...
class UnsupportedThinkingModeError(GrokClientError): ...
class GrokClientBatchError(GrokClientError): ...
class GrokClientMultimodalError(GrokClientError): ...
class GrokClientCacheError(GrokClientError): ...

def wrap_logger_error(exc: Exception, message: str) -> GrokLoggerError: ...
def wrap_infopypg_error(exc: Exception, message: str) -> GrokInfopypgError: ...
def wrap_postgres_error(exc: Exception, message: str) -> GrokPostgresError: ...
def wrap_grok_api_error(exc: Exception, message: str) -> GrokAPIError: ...
